### Health Check

GET http://localhost:3000/health HTTP/1.1

### Get user by ID

GET http://localhost:3000/users/1 HTTP/1.1

### Get user by ID include soft-deleted users

GET http://localhost:3000/users/with-soft-deletes/1 HTTP/1.1

### Create a new user

POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@doe.com"
}

### Create a new user called Soft Delete

POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "name": "Soft Delete",
    "email": "soft@softdelete.com"
}

### Update a user

PUT http://localhost:3000/users/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Alex Doe"
}

### Delete a user

DELETE http://localhost:3000/users/1 HTTP/1.1

### Delete a user Soft Delete

DELETE http://localhost:3000/users/2 HTTP/1.1

### Get all users

GET http://localhost:3000/users HTTP/1.1

### 404 Example

GET http://localhost:3000/unknown HTTP/1.1

### Create a post for a user

POST http://localhost:3000/posts HTTP/1.1
Content-Type: application/json

{
    "user_id": 1,
    "title": "My First Post",
    "content": "This is the content of my first post.",
    "tags": [
        "introduction",
        "firstpost"
    ]
}

### List user's posts

GET http://localhost:3000/users/1/posts HTTP/1.1

### List posts

GET http://localhost:3000/posts HTTP/1.1

### List posts by tag

GET http://localhost:3000/tags/1/posts HTTP/1.1